language: ruby
services: docker
cache:
- bundler
before_install:
  gem install bundler -v 2.2.16
install:
- bundle install
rvm:
- 2.4.1
- 2.5.8
script:
- bundle exec rake default
- gem build sensu-plugins-aws.gemspec
- gem install sensu-plugins-aws-*.gem
